-- Brown Derby customer ordering portal
-- Run this in the Supabase SQL editor once the Supabase project is connected.

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_email text not null,
  customer_business_name text not null default '',
  customer_contact_name text not null default '',
  status text not null default 'draft' check (status in ('draft', 'submitted')),
  notes text not null default '',
  email_status text not null default 'not_sent' check (email_status in ('not_sent', 'sent', 'failed')),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  category text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0 and quantity <= 9999),
  created_at timestamptz not null default now(),
  unique (order_id, product_id)
);

create unique index if not exists one_draft_per_customer
  on public.orders(user_id)
  where status = 'draft';

create index if not exists orders_user_created_idx
  on public.orders(user_id, created_at desc);

create index if not exists order_items_order_idx
  on public.order_items(order_id);

create or replace function public.touch_order_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at
before update on public.orders
for each row execute function public.touch_order_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Browser clients do not access these tables directly. All order access goes
-- through authenticated Next.js server routes, which verify the Supabase user
-- and then scope every query to that user's UUID.
revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
grant all on public.orders to service_role;
grant all on public.order_items to service_role;
grant usage, select on all sequences in schema public to service_role;
